### ISSUE TITLE
Finding the right Batching protocol

### ISSUE THREAD

**Issue by smyrick** [graphql/composite-schemas-spec#27] opened 2024-03-28 16:22 UTC
Separate from the [Batching Mechanism](https://github.com/graphql/composite-schemas-spec/issues/25) (the payload format inside the request/protocol), we need to discuss how the data can be returned for a batched request.

So far we have discussed:
* HTTP Multipart
* SSE
* JSONL

Benjie has written up a small gist of all these here:
https://gist.github.com/benjie/f696f494878ddebb423c978ccb3a39df

**Comment by smyrick** [comment] 2024-04-02 19:38
We discussed at the meeting on 2024-03-28 that maybe this should be pushed outside of this group and part of the GraphQL over HTTP WG. We could defer to that protocol elsewhere and just in this spec say that we can return a list of responses and how that is done is decided outside this spec

**Comment by michaelstaib** [comment] 2024-08-29 11:24
Duplicate of #25

**Closed by michaelstaib** 2024-08-29 11:24 UTC
